In [4]:
import pandas as pd

data = {

        "姓名": ["张三", "李四", "王五", "赵六"],

        "年龄": [25, 30, 28, 35],

        "城市": ["北京", "上海", "北京", "深圳"]

    }

df = pd.DataFrame(data)
df

   姓名  年龄  城市
0  张三  25  北京
1  李四  30  上海
2  王五  28  北京
3  赵六  35  深圳

In [5]:
df.info()

df.describe()

df.head(2)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      4 non-null      str
 1   年龄      4 non-null      int64
 2   城市      4 non-null      str
dtypes: int64(1), str(2)
memory usage: 224.0 bytes

   姓名  年龄  城市
0  张三  25  北京
1  李四  30  上海