In [4]:
import pandas as pd

data = {

        "姓名": ["张三", "李四", "王五", "赵六"],

        "年龄": [25, 30, 28, 35],

        "城市": ["北京", "上海", "北京", "深圳"]

    }

df = pd.DataFrame(data)
df

   姓名  年龄  城市
0  张三  25  北京
1  李四  30  上海
2  王五  28  北京
3  赵六  35  深圳

In [5]:
df.info()

df.describe()

df.head(2)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      4 non-null      str
 1   年龄      4 non-null      int64
 2   城市      4 non-null      str
dtypes: int64(1), str(2)
memory usage: 224.0 bytes

   姓名  年龄  城市
0  张三  25  北京
1  李四  30  上海

In [ ]:
# ===== 1. 选取列 =====
df['姓名']          # 选一列 → 返回 Series（一维，带索引）

In [ ]:
df[['姓名', '城市']]  # 选多列 → 返回 DataFrame（二维，注意是双层中括号）

In [ ]:
# ===== 2. 选取行（loc 用标签名，iloc 用位置号）=====
df.loc[0]           # 选第0行（标签是0）

In [ ]:
df.loc[0:2]         # 选第0~2行（注意：loc 的切片是"包含"末尾的！）

In [ ]:
df.iloc[0:2]        # 选第0~1行（iloc 的切片"不包含"末尾，跟 Python 切片一样）

In [ ]:
# ===== 3. 同时选行和列 =====
df.loc[0, '姓名']            # 第0行的姓名 → 张三

In [ ]:
df.loc[[0, 1], ['姓名', '城市']]  # 第0、1行的姓名和城市

In [ ]:
# ===== 4. 条件筛选（最实用！）=====
df[df['年龄'] > 28]                    # 年龄大于28的人

In [ ]:
df[df['城市'] == '北京']               # 城市是北京的人

In [ ]:
df[(df['年龄'] > 25) & (df['城市'] == '北京')]  # 两个条件：年龄>25 且 城市北京
# 注意：& 表示"且"，每个条件要套括号！

In [ ]:
# ===== 5. 选取特定值 =====
df['年龄'].max()    # 最大年龄

In [ ]:
df['年龄'].min()    # 最小年龄

In [ ]:
df['年龄'].mean()   # 平均年龄

In [ ]:
# ===== 6. 新增列 =====
df['工资'] = [8000, 12000, 9000, 15000]   # 直接赋值一个列表，列就加上了
df

In [ ]:
# ===== 7. 修改数据 =====
df.loc[0, '年龄'] = 26      # 把第0行（张三）的年龄改成26
df['城市'] = df['城市'].replace('北京', '北京市')  # 把所有"北京"改成"北京市"
df

In [ ]:
# ===== 8. 排序 =====
df.sort_values('年龄')              # 按年龄从小到大排（默认升序）
df.sort_values('年龄', ascending=False)  # 降序排（从大到小）
df.sort_values(['城市', '工资'], ascending=[True, False])  # 先按城市升序，城市相同再按工资降序

In [ ]:
# ===== 9. 分组 groupby（超重要！）=====
# 按城市分组，算每组的平均工资
df.groupby('城市')['工资'].mean()

In [ ]:
# 分组后可以同时算多个统计量
df.groupby('城市')['工资'].agg(['mean', 'max', 'min', 'count'])
# mean=平均, max=最大, min=最小, count=人数

In [ ]:
# ===== 10. 删除行/列 =====
df.drop(columns=['工资'])        # 删掉"工资"列（注意：原 df 不变，返回新的）
df.drop(index=0)                 # 删掉第0行

In [ ]:
# ===== 11. 读写 CSV 文件 =====
# 保存到文件（会在当前目录生成 people.csv）
df.to_csv('people.csv', index=False)   # index=False 表示不保存行号

# 再读回来
pd.read_csv('people.csv')